services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:5001"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: gnammy_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - db_data:/var/lib/mysql
      - ./db_gnammy.sql:/docker-entrypoint-initdb.d/db_gnammy.sql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
